#ifndef GNURADIO_DASHBOARDBRIDGE_HPP
#define GNURADIO_DASHBOARDBRIDGE_HPP

#include <cstddef>
#include <gnuradio-4.0/Block.hpp>
#include <gnuradio-4.0/BlockRegistry.hpp>
#include <gnuradio-4.0/Tag.hpp>
#include <gnuradio-4.0/annotated.hpp>
#include <gnuradio-4.0/meta/reflection.hpp>
#include <thread>
#include <websocketpp/common/connection_hdl.hpp>
#include <websocketpp/config/asio_no_tls.hpp>
#include <websocketpp/roles/server_endpoint.hpp>
#include <websocketpp/server.hpp> 


#include <fstream>
#include <sstream>
#include <functional>
#include <nlohmann/json.hpp> 



//Block sections 
//Section for defining the block 
//Section for defining the asynchronous sever for networking
//Section for defining the work the block does during run time


namespace gr::indep_imGUI_timeSeries{


    using namespace gr;

    typedef websocketpp::server<websocketpp::config::asio> server;
    //Network state
    enum BlockState {
        DISCONNECTED,
        WAITING_CONNECTION,
        SENDING_CONFIG,
        AWAITING_CONFIG_ACK,
        STREAMING
    };


    template<typename T>
    struct indep_timeSeries : Block<indep_timeSeries<T>> {


        //TO DO: Add description 
        //using Description = gr::Doc<>


        //Single Port for now
        //TO DO: Consider multiport functionality
        //1) This will prevent use of processOne i think (May not make sense anywas as we are packaging some sample data and sending it not a single sample)
        PortIn<T> dataStream;

        //Single Port number for now
        //TO DO: Make port allocation automatic
        //TO DO: Given multiport functionality, number of port variables must be a vector of values 
        //Size of the number of input ports 
        Annotated<size_t, "Port_Number",Visible, Doc<"Port used by block to reach network">> num_port;

        //To DO: Should be generated by some part of the flowgraph
        gr::Annotated<std::string, "configFile_path", gr::hidden>> configFile_path;


        //TO DO: Ask what exactly is the property map because i dont think i fully understand it
        //Should i expliclty intialize it in my constructor ?
        indep_timeSeries(gr::property_map initial_settings = {}) : gr::Block<indep_timeSeries<T>>(initial_settings) {}

        //Or use this approach i found in the PeakDectector block
        //void settingsChanged(const property_map& /*old*/, const property_map& /*new*/) noexcept { start(); }


        //Reflection
        GR_MAKE_REFLECTABLE(indep_timeSeries,dataStream,num_port,config_file);


        //Internal variables declarations
        //TO DO: Ask how i can generate the config file and link it within the block
        //TO DO: Ask how i can keep the path consistent for the config file
        server sinkServer;
        std::set<websocketpp::connection_hdl, std::owner_less<websocketpp::connection_hdl>> sinkServerConnections;
        std::thread sinkServer;

        void start() 
        {
            try
            {
                //Start the aysnchronous communication
                sinkServer.init_asio();


                //Function triggeres on connection (Check Dashboard Sent)
                //Need this so that the lamda experssion can access the variables and functions of the block
                sinkServer.set_open_handler([this](websocketpp::connection_hdl hdl)){

                    //Store connection "ID"
                    sinkServer.insert(hdl)
                    
                    //TO DO: Since there isnt really a way to trigger feedback except within the function itself
                    //What is the standard practice for printing feedback such as "FrontEnd Connected"
                    
                    ///Sending Over Message for checking if dashboard has been sent
                    //






                }












            }





















        }













    }















}